# Generated by Django 4.0.3 on 2022-06-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_auto_20190818_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='booked_time_slot',
            field=models.CharField(blank=True, choices=[('10:00 AM - 2:00 PM', '10:00 AM - 2:00 PM'), ('3:00 PM - 7:00 PM', '3:00 PM - 7:00 PM'), ('8:00 PM - 10:00 PM', '8:00 PM - 10:00 PM')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BKASH', 'Bkash'), ('CREDIT CARD', 'Credit Card'), ('ON SPOT', 'On Spot')], max_length=20, null=True),
        ),
    ]
