# Generated by Django 4.0.3 on 2022-06-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_alter_testorder_booked_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='booked_time_slot',
            field=models.CharField(blank=True, choices=[('10:00 AM - 12:00 PM', '10:00 AM - 12:00 PM'), ('1:00 PM - 3:00 PM', '1:00 PM - 3:00 PM'), ('3:00 PM - 5:00 PM', '3:00 PM - 5:00 PM'), ('5:00 PM - 8:00 PM', '5:00 PM - 8:00 PM')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('CREDIT CARD', 'Credit Card'), ('ON SPOT', 'On Spot')], max_length=20, null=True),
        ),
    ]
